### ISSUE TITLE
Feature request: posts and pages automatically assigned to a section

### ISSUE THREAD

**Issue by aldemarcalazans** [bu-ist/bu-section-editing#11]
It would be great if we could assign a post to a Section, according to its category. Due their hierarchical characteristic, it's easy to assign a page and it's descendants to a Section, using the interface resources. But, with posts, it is much more difficult: as neither of them has hierarchical relation with any page or post: we have to select all desired posts, one by one, which is terribly tedious in a installation with thousands of them.

If we could inform the plugin that we want to select all post of a specified category, the task above would be much more easy!

But, the perfection in code development would be achieved if every new post of a category and every new page descendant (from a previously chosen one) could automatically be included in a Section.
For compatibility reasons, certainly this features should be optional, selected via checkboxes.

**Comment by awbauer** [comment]
Thank you for the feedback,@aldemarcalazans! The ability to add whole categories to a section sounds like a great feature. I'll share it with the team & see if we can work it into our roadmap.

**Comment by louiswalch** [comment]
Hello, I wanted to check on this feature. I have a custom post type and would like any new post within this to be automatically assigned to a group rather then requiring an admin to add on one-by-one basis.

**Comment by anton-kachurin** [comment]
In version 0.9.9 it's possible to mark all posts of a certain custom type editable by some section group. Also, that would allow to add new posts of this type by the section group's editors.
