### ISSUE TITLE
Permissions and categories?

### ISSUE THREAD

**Issue by mindctrl** [bu-ist/bu-section-editing#7]
First off, I want to say I **love** this plugin. I love the simplicity of the interface and that the plugin does exactly what it's supposed to do and does it well. Thank you for that!

I have a question.

Is there a way to define permissions based on categories or other taxonomies? Is that doable via the custom roles mentioned in the wiki? Said another way, instead of defining permissions to specific posts or pages, could I, for example, allow User B access to all posts in Category B or all posts in Custom Taxonomy B?

**Comment by anton-kachurin** [comment]
In version 0.9.9 it's possible to mark all posts of a certain custom type editable by some section group. Also, that would allow to add new posts by this section group's editors.
